FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

SRC_URI:append = " file://fstab"

# The machine's plaintext var partition: a /dev/disk/by-partlabel/<name> path,
# a PARTUUID=<uuid>, a raw /dev/<node>, or "none" when init mounts /var itself
# (avocado-tegra-init).
AVOCADO_VAR_PART_DEV ?= "PARTUUID=4d21b016-b534-45c2-a9fb-5c16e091fd2d"

# /var is mounted from /dev/disk/by-avocado/var, not from AVOCADO_VAR_PART_DEV
# directly. The rule written here points that name at the plaintext partition;
# cryptsetup-var's 99-zz rule points it at the LUKS mapping with a higher
# link_priority whenever the initrd opened one. So one fstab serves a runtime
# that opted into encryption (avocado.yaml var.encrypt) and one that did not,
# and the build never has to know which (docs/security-capabilities.md).
# udev match for the plaintext partition, from the three forms above.
def avocado_var_udev_match(d):
    dev = d.getVar('AVOCADO_VAR_PART_DEV') or ''
    if dev.startswith('/dev/disk/by-partlabel/'):
        return 'ENV{ID_PART_ENTRY_NAME}=="%s"' % dev.rsplit('/', 1)[-1]
    if dev.startswith('/dev/disk/by-partuuid/') or dev.startswith('PARTUUID='):
        return 'ENV{ID_PART_ENTRY_UUID}=="%s"' % dev.rsplit('/', 1)[-1].split('=', 1)[-1]
    # A bare kernel node only: KERNEL== matches names like mmcblk0p3, never a
    # path, so any other /dev/disk/by-* form would generate a rule that is valid
    # udev and never fires - and /var would silently never mount.
    if dev.startswith('/dev/') and '/' not in dev[len('/dev/'):]:
        return 'KERNEL=="%s"' % dev[len('/dev/'):]
    if dev == 'none':
        return ''
    bb.fatal("AVOCADO_VAR_PART_DEV='%s': expected /dev/disk/by-partlabel/<name>, /dev/disk/by-partuuid/<uuid>, PARTUUID=<uuid>, /dev/<node> or none" % dev)

AVOCADO_VAR_UDEV_MATCH = "${@avocado_var_udev_match(d)}"

do_install:append() {
    install -m 0644 ${UNPACKDIR}/fstab ${D}${sysconfdir}/fstab
    if [ "${AVOCADO_VAR_PART_DEV}" = "none" ]; then
        sed -i '/@AVOCADO_VAR_PART_DEV@/d' ${D}${sysconfdir}/fstab
        return
    fi
    sed -i 's|@AVOCADO_VAR_PART_DEV@|/dev/disk/by-avocado/var|g' ${D}${sysconfdir}/fstab

    install -d ${D}${nonarch_base_libdir}/udev/rules.d
    cat > ${D}${nonarch_base_libdir}/udev/rules.d/61-avocado-var.rules <<EOF
# Generated by base-files from AVOCADO_VAR_PART_DEV=${AVOCADO_VAR_PART_DEV}.
# The plaintext /var partition claims /dev/disk/by-avocado/var; once it carries a
# LUKS header it stops claiming it, and the opened "var" dm mapping claims it
# instead. Deciding on ID_FS_TYPE rather than on link priority alone keeps the
# name from ever pointing at the raw LUKS partition during coldplug, where
# var.mount would otherwise race the mapping and fail. Both lines live here, in
# base-files, because this file is in the initramfs as well as the rootfs: the
# initrd is where the mapping is created and where var.mount first needs the
# name (cryptsetup-var-udev's 99-zz rule is rootfs-only).
# ID_FS_TYPE=="?*" first: udev's negative match is also satisfied when the
# property is unset, and it is only populated once 60-persistent-storage's
# blkid import has run - so an event without it must not claim the name either.
SUBSYSTEM=="block", ACTION=="add|change", ${AVOCADO_VAR_UDEV_MATCH}, ENV{ID_FS_TYPE}=="?*", ENV{ID_FS_TYPE}!="crypto_LUKS", SYMLINK+="disk/by-avocado/var"
SUBSYSTEM=="block", ACTION=="add|change", KERNEL=="dm-[0-9]*", ATTR{dm/name}=="var", SYMLINK+="disk/by-avocado/var", OPTIONS+="link_priority=100"
EOF
}
do_install[vardeps] += "AVOCADO_VAR_PART_DEV"

FILES:${PN} += "${nonarch_base_libdir}/udev/rules.d/61-avocado-var.rules"
