#@TYPE: Machine
#@NAME: NXP i.MX 91 FRDM
#@DESCRIPTION: NXP i.MX 91 FRDM development board

BOOTVARS = "ubootenv"
STONE_PROVISIONING ?= "img sd uuu-emmc"
MACHINEOVERRIDES =. "bootvars-${BOOTVARS}:imx91-frdm:imx91-11x11-lpddr4-frdm:"

require conf/machine/include/avocado.inc
require conf/machine/include/avocado-imx.inc
require conf/machine/include/avocado-imx-frdm.inc

require conf/machine/imx91-11x11-lpddr4-frdm.conf
require conf/machine/include/fsl-imx-preferred-env.inc

UBOOT_ENV_SIZE = "0x20000"
