#@TYPE: Machine
#@NAME: NXP i.MX 93 FRDM
#@DESCRIPTION: NXP i.MX 93 FRDM development board

BOOTVARS = "ubootenv"
STONE_PROVISIONING ?= "img sd uuu-emmc"
MACHINEOVERRIDES =. "bootvars-${BOOTVARS}:imx93-frdm:imx93-11x11-lpddr4x-frdm:"

require conf/machine/include/avocado.inc
require conf/machine/include/avocado-imx.inc
require conf/machine/include/avocado-imx-frdm.inc

require conf/machine/imx93-11x11-lpddr4x-frdm.conf
require conf/machine/include/fsl-imx-preferred-env.inc

UBOOT_ENV_SIZE = "0x20000"
