#@TYPE: Machine
#@NAME: NXP i.MX 8MP EVK
#@DESCRIPTION: NXP i.MX 8MP EVK development board

require conf/machine/include/avocado.inc

MACHINEOVERRIDES =. "imx8mp-lpddr4-evk:"

require conf/machine/imx8mp-lpddr4-evk.conf
