#@TYPE: Machine
#@NAME: NXP i.MX 93 EVK
#@DESCRIPTION: NXP i.MX 93 EVK development board

BOOTVARS = "ubootenv"
STONE_PROVISIONING ?= "img sd"
MACHINEOVERRIDES =. "bootvars-${BOOTVARS}:imx93-evk:imx93-11x11-lpddr4x-evk:"

require conf/machine/include/avocado.inc
require conf/machine/include/avocado-imx.inc

UBOOT_ENV_SIZE = "0x20000"

require conf/machine/imx93-11x11-lpddr4x-evk.conf
