#@TYPE: Machine
#@NAME: NXP i.MX 91 FRDM
#@DESCRIPTION: NXP i.MX 91 FRDM development board

require conf/machine/include/avocado.inc
require conf/machine/imx91-11x11-lpddr4-frdm.conf
require conf/machine/include/fsl-imx-preferred-env.inc

BOOTVARS = "ubootenv"
MACHINEOVERRIDES =. "stone-validate:bootvars-${BOOTVARS}:imx91-frdm:imx91-11x11-lpddr4-frdm:"

UBOOT_ENV_SIZE = "0x20000"
