#@TYPE: Machine
#@NAME: NXP i.MX 93 EVK
#@DESCRIPTION: NXP i.MX 93 EVK development board

require conf/machine/include/avocado.inc

BOOTVARS = "ubootenv"
MACHINEOVERRIDES =. "bootvars-${BOOTVARS}:imx93-evk:imx93-11x11-lpddr4x-evk:"

UBOOT_ENV_SIZE = "0x20000"

require conf/machine/imx93-11x11-lpddr4x-evk.conf
