#@TYPE: Machine
#@NAME: NXP i.MX 8MP EVK
#@DESCRIPTION: NXP i.MX 8MP EVK development board

require conf/machine/include/avocado.inc

BOOTVARS = "ubootenv"
MACHINEOVERRIDES =. "stone-validate:bootvars-${BOOTVARS}:imx8mp-evk:imx8mp-lpddr4-evk:"

UBOOT_ENV_SIZE = "0x20000"

require conf/machine/imx8mp-lpddr4-evk.conf
