# SPDX-License-Identifier: Apache-2.0

"""Render the repository sections written into a target's generated .repo file.

Extracted from avocado-sdk-metadata.bb so the emitted block can be asserted on
without a build. What the client is told to verify is a security decision, and
until now it was only observable by building an SDK and reading the file out of
it.

dnf keeps two independent options here and the recipe only ever emitted one:

``gpgcheck``
    verifies *package* signatures. Avocado does not sign packages, so this stays
    off regardless of anything below.

``repo_gpgcheck``
    verifies the *repository index* against a detached ``repomd.xml.asc``. This
    is the one a signed feed needs, and the name of the recipe variable that
    drove ``gpgcheck`` (``AVOCADO_REPO_GPGCHECK``) reads as though it already
    did this. It did not.

Both default off. Turning ``repo_gpgcheck`` on before the feed publishes
signatures breaks every install, so the switch belongs with the publisher
change, not ahead of it.

devtool-debt: only the sections generated by avocado-sdk-metadata.bb render
through here. The [avocado-sdk] section is a static file installed by
avocado-sdk-repos.bb and carries a hardcoded gpgcheck=0 with no repo_gpgcheck.
Ceiling: adequate only while metadata verification is off everywhere.
Upgrade trigger: bring that recipe through this renderer before anything sets
AVOCADO_REPO_METADATA_GPGCHECK=1, or the SDK repo every container reads stays
unverified while the generated ones are verified.
"""

# Relative to the repository root, which is also what baseurl points at.
_KEY_RELPATH = "repodata/repomd.xml.key"

# dnf parses both switches as booleans. Anything else is read as false, so a
# typo would silently disable verification rather than fail - which is the one
# outcome a security option must not have.
_BOOLEAN = ("0", "1")


def render_repo_section(
    *,
    section,
    name,
    baseurl_path,
    priority,
    gpgcheck="0",
    repo_gpgcheck="0",
):
    """Return one ``[section]`` block, including its trailing blank separator.

    ``baseurl_path`` is appended to the ``${repo_url}`` placeholder, which is
    substituted by the client at SDK install time rather than at build time.

    Raises:
        ValueError: ``baseurl_path`` is empty, which would point the client at
            the feed root, or either verification switch is not a dnf boolean.
    """
    if not baseurl_path:
        raise ValueError(f"repo section {section!r} has no baseurl path")
    for option, value in (("gpgcheck", gpgcheck), ("repo_gpgcheck", repo_gpgcheck)):
        if value not in _BOOLEAN:
            raise ValueError(
                f"repo section {section!r}: {option} must be one of "
                f"{_BOOLEAN}, got {value!r}"
            )

    baseurl = "${repo_url}/" + baseurl_path

    lines = [
        f"[{section}]",
        f"name={name}",
        f"baseurl={baseurl}",
        "enabled=1",
        f"gpgcheck={gpgcheck}",
        f"repo_gpgcheck={repo_gpgcheck}",
    ]
    if repo_gpgcheck == "1":
        # Only advertised alongside verification: the key is published by the
        # same step that publishes the signature, so referencing it while
        # verification is off points at a 404.
        lines.append(f"gpgkey={baseurl}/{_KEY_RELPATH}")
    lines.append(f"priority={priority}")

    return "\n".join(lines) + "\n\n"
