# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-avocado-alif"
BBFILE_PATTERN_meta-avocado-alif = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-avocado-alif = "9"

LAYERDEPENDS_meta-avocado-alif = "core meta-alif meta-alif-ensemble"
LAYERSERIES_COMPAT_meta-avocado-alif = "scarthgap"
