# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-avocado-qcom"
BBFILE_PATTERN_meta-avocado-qcom = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-avocado-qcom = "9"

LAYERDEPENDS_meta-avocado-qcom = "core qcom"
LAYERSERIES_COMPAT_meta-avocado-qcom = "wrynose"
