#@TYPE: Machine
#@NAME: avocado-rubikpi3
#@DESCRIPTION: Machine configuration for the Rubik Pi 3 board, based on Qualcomm 6490 SoC

MACHINEOVERRIDES =. "rubikpi3:"

require conf/machine/include/avocado.inc
require conf/machine/include/qcom-qcs6490.inc

MACHINE_FEATURES = "usbhost usbgadget"

# This DT currently exist only as patches against linux-qcom-base recipe.
KERNEL_DEVICETREE:pn-linux-qcom-base = "qcom/qcm6490-idp.dtb"

KERNEL_DEVICETREE:pn-linux-qcom-custom = "qcom/qcs6490-thundercomm-rubikpi3.dtb"

# Additional dtbo to overylay on top of kernel devicetree files
KERNEL_TECH_DTBOS[rubikpi3] = "qcm6490-graphics.dtbo \
    qcm6490-video.dtbo \
    rubikpi3-overlay.dtbo"

KERNEL_TECH_DTBOS[qcm6490-addons-idp-amoled] = "qcm6490-graphics.dtbo \
    qcm6490-video.dtbo"

# Recipe providers of above dtbo files.
KERNEL_TECH_DTBO_PROVIDERS = "qcom-graphicsdevicetree \
    qcom-videodtb \
    rubikpi3-dtbo"

CONSOLE_CMDLINE ?= "console=ttyMSM0,115200n8 earlycon"
SERIAL_CONSOLES ?= "115200;ttyMSM0"

AVOCADO_VAR_PART_DEV = "/dev/disk/by-partlabel/avocado"
