# This class generates the avocado-repo.map file used by the staging scripts
# to determine how to deploy RPM packages to the repository server.
#
# The map file is generated by scanning DEPLOY_DIR_RPM for existing directories
# and mapping each one to its corresponding repository path.
#
# This class should be inherited by meta-target recipes like avocado-distro
# and avocado-sdk to ensure the map file is generated after all packages
# are built and deployed.
#
# The task is idempotent - running it multiple times produces the same result
# based on the current state of DEPLOY_DIR_RPM. This allows both distro and SDK
# builds to safely inherit this class when built together.

inherit avocado-arch-utils

python do_create_repo_map() {
    import os
    import bb

    deploy_dir_rpm = d.getVar('DEPLOY_DIR_RPM')
    bb.note(f"Creating repo map from DEPLOY_DIR_RPM: {deploy_dir_rpm}")

    if not os.path.isdir(deploy_dir_rpm):
        bb.warn(f"DEPLOY_DIR_RPM does not exist: {deploy_dir_rpm}")
        return

    # Scan DEPLOY_DIR_RPM for all existing directories
    existing_dirs = []
    for entry in os.listdir(deploy_dir_rpm):
        entry_path = os.path.join(deploy_dir_rpm, entry)
        if os.path.isdir(entry_path):
            existing_dirs.append(entry)

    bb.note(f"Found {len(existing_dirs)} directories in DEPLOY_DIR_RPM: {existing_dirs}")

    # Build the map file content
    map_entries = []

    for arch_dir in sorted(existing_dirs):
        # Convert directory name back to arch format (underscores to hyphens for lookup)
        # But for the map file, we use the directory name as-is
        arch = arch_dir.replace('_', '-')

        # Skip sdk-provides-dummy architectures
        if arch.startswith('sdk-provides-dummy'):
            continue

        # Determine the repo path for this arch
        repo_details = avocado_determine_repo_paths(d, arch, arch_dir)

        if repo_details["map_value_path"]:
            map_entries.append(f"{arch_dir}={repo_details['map_value_path']}")
            bb.note(f"Map entry: {arch_dir}={repo_details['map_value_path']}")
        else:
            bb.warn(f"No map path determined for arch_dir '{arch_dir}'")

    # Write the map file
    map_file_path = os.path.join(deploy_dir_rpm, 'avocado-repo.map')

    with open(map_file_path, 'w') as map_f:
        for entry in map_entries:
            map_f.write(entry + '\n')

    bb.note(f"Wrote {len(map_entries)} entries to {map_file_path}")
}

# Task should always run (no stamp) since it reflects current state of deploy directory
do_create_repo_map[nostamp] = "1"

# This function is called explicitly by recipes that inherit this class
# (e.g., avocado-complete calls it from do_compile)
