# Make the kernel-base package emit `Provides: kernel-module-X` for every
# module that's compiled into the kernel image (CONFIG_X=y). Inherited by
# each kernel bbappend in meta-avocado-{family}/recipes-kernel/linux/
# alongside avocado-kernel-feed.
#
# Why: oe-core recipes (systemd, cryptsetup, systemd-zram-generator, ...)
# carry unqualified `RRECOMMENDS: kernel-module-X` for kernel features they
# expect to be present. In a multi-kernel feed those recommends NVR-tiebreak
# across kernels — and when a kernel has the feature compiled in (=y) rather
# than modular (=m), there's no `kernel-module-X-${KERNEL_VERSION}` package
# in that kernel's PACKAGES set, so dnf falls back to a different kernel's
# modular variant, pulling cross-kernel modules and the off-kernel base
# package into the rootfs. With this class, the kernel's own base package
# accurately advertises every built-in module as an unqualified Provide;
# the recommend is satisfied by the installed kernel itself.
#
# Source of truth is ${B}/modules.builtin, generated by Kbuild during
# do_compile. The list is intersected with the kernel-module package naming
# convention (s/_/-/g) so the Provides line up with the names oe-core
# recipes use in their RRECOMMENDS.

python avocado_kernel_emit_builtin_provides() {
    import os

    builtin = os.path.join(d.getVar("B") or "", "modules.builtin")
    if not os.path.isfile(builtin):
        bb.warn("avocado-kernel-builtin-provides: %s missing; skipping "
                "(do_compile must produce modules.builtin)" % builtin)
        return

    kver = d.getVar("KERNEL_VERSION")
    kpn = d.getVar("KERNEL_PACKAGE_NAME") or "kernel"
    if not kver:
        return
    # kernel.bbclass keys subpackage variables on the UNQUALIFIED sub-name
    # (e.g. "kernel-base") and renames to "${KERNEL_PACKAGE_NAME}-${KERNEL_VERSION}"
    # at the end via PKG:kernel-base. Setting RPROVIDES on the renamed name
    # would be ignored — set it on the unqualified sub-name so the carried-
    # through value lands in the final RPM's metadata.
    base_pkg = "%s-base" % kpn

    # Emit BOTH unqualified and qualified forms for every built-in module.
    #
    # - Unqualified `kernel-module-X`: satisfies upstream oe-core RRECOMMENDS
    #   in systemd / cryptsetup / etc. that reference modules by bare name.
    # - Qualified `kernel-module-X-${KERNEL_VERSION}`: satisfies references
    #   that have been suffixed with the resolver's pinned kver — either by
    #   avocado-cli's auto-suffix on user yaml (`kernel-module-X` becomes
    #   `kernel-module-X-${kver}` before the dnf install line) or by an
    #   explicit `{{ avocado.kernel.version }}` template in user yaml.
    #
    # Without the qualified emit, suffix-templated references for built-in
    # modules 404 because no rpm with that exact NAME exists in the feed.
    # The kernel-base advertising the qualified name lets dnf satisfy the
    # reference from the kernel package itself.
    seen = set()
    provides = []
    with open(builtin) as f:
        for line in f:
            path = line.strip()
            if not path:
                continue
            modname = os.path.splitext(os.path.basename(path))[0]
            base = "kernel-module-%s" % modname.replace("_", "-")
            for pkgmod in (base, "%s-%s" % (base, kver)):
                if pkgmod in seen:
                    continue
                seen.add(pkgmod)
                provides.append(pkgmod)

    if not provides:
        return

    # Drop any Provides that would shadow a modular kernel-module-* rpm this
    # same kernel recipe is also producing.
    #
    # Why: kernel-module-split.bbclass names a split package after the .ko
    # basename. The kernel source tree can contain two distinct .ko files
    # that share a basename (e.g. drivers/bus/arm-cci.ko built-in via
    # CONFIG_ARM_CCI=y and drivers/perf/arm-cci.ko modular via
    # CONFIG_ARM_CCI_PMU=m; same shape for net/tls/tls.ko vs
    # crypto/tls.ko). In that case modules.builtin lists `arm-cci.ko` and
    # kernel-module-split simultaneously emits `kernel-module-arm-cci.rpm`
    # for the modular sibling. Without this filter we'd emit
    # `Provides: kernel-module-arm-cci` on kernel-base AND publish a
    # separate kernel-module-arm-cci rpm — dnf sees two candidates for the
    # same name and may pick the kernel package, leaving the modular rpm
    # uninstallable.
    #
    # PACKAGES is populated by kernel-module-split's split_kernel_module_packages
    # before emit_pkgdata. In Avocado kernel recipes the module split names
    # already include the KERNEL_VERSION suffix ("kernel-module-X-${kver}")
    # because KERNEL_MODULE_PACKAGE_SUFFIX is set on multi-kernel builds.
    # Strip that suffix to recover the bare module name and use it as the
    # collision key against both the unqualified and qualified Provides
    # we're about to emit.
    pkg_list = (d.getVar("PACKAGES") or "").split()
    kver_suffix = "-%s" % kver
    modular = set()
    for p in pkg_list:
        if not p.startswith("kernel-module-"):
            continue
        bare = p[: -len(kver_suffix)] if p.endswith(kver_suffix) else p
        modular.add(bare)

    if modular:
        dropped = []
        kept = []
        for p in provides:
            bare = p[: -len(kver_suffix)] if p.endswith(kver_suffix) else p
            if bare in modular:
                dropped.append(p)
            else:
                kept.append(p)
        if dropped:
            bb.note("avocado-kernel-builtin-provides: dropped %d Provides "
                    "shadowing modular kernel-module rpms: %s"
                    % (len(dropped), " ".join(sorted(dropped))))
        provides = kept

    if not provides:
        return

    existing = (d.getVar("RPROVIDES:%s" % base_pkg) or "").split()
    merged = list(dict.fromkeys(existing + provides))
    d.setVar("RPROVIDES:%s" % base_pkg, " ".join(merged))
    bb.note("avocado-kernel-builtin-provides: emitted %d builtin Provides on %s"
            % (len(provides), base_pkg))
}

# Insert our function immediately before emit_pkgdata in PACKAGEFUNCS.
# emit_pkgdata is the function that snapshots the datastore RPROVIDES into
# the per-package pkgdata files; anything that runs after it is invisible
# to the rpm builder. PACKAGEFUNCS:append puts us at the end (after
# emit_pkgdata — too late). The :remove + :append trick doesn't work
# either because bitbake applies :remove *last* and removes *every*
# occurrence — including the one we tried to re-append, so emit_pkgdata
# vanishes from the run entirely and per-package rpms aren't emitted.
# A Python anonymous function lets us splice into the list at a precise
# index after parse, with no operator-ordering surprises.
python __anonymous() {
    pf = (d.getVar("PACKAGEFUNCS") or "").split()
    if "avocado_kernel_emit_builtin_provides" in pf:
        return
    if "emit_pkgdata" not in pf:
        bb.warn("avocado-kernel-builtin-provides: emit_pkgdata not in PACKAGEFUNCS; "
                "skipping insertion")
        return
    idx = pf.index("emit_pkgdata")
    pf.insert(idx, "avocado_kernel_emit_builtin_provides")
    d.setVar("PACKAGEFUNCS", " ".join(pf))
}

