services:
  package-repo:
    build:
      context: ../package-repo
      dockerfile: Containerfile
    ports:
      - "8080:80"
    volumes:
      - ${DEPLOY_DIR}/rpm:/repo:ro
    # Add healthcheck configuration
    healthcheck:
      # Command to run inside the container to check health
      # Here we try to curl the base URL. Adjust if your repo server needs a different check.
      # '-f' fails silently on HTTP errors but returns non-zero exit code
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s  # Check every 10 seconds
      timeout: 5s    # Wait up to 5 seconds for the check to complete
      retries: 5     # Try 5 times before marking as unhealthy
      start_period: 15s # Grace period for startup before first check failure counts

  sdk:
    image: avocadolinux/sdk:dev
    depends_on:
      package-repo:
        condition: service_healthy
    entrypoint: /entrypoint.sh
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./run_qemu.sh:/run_qemu.sh:ro
      - ./build_var.sh:/build_var.sh:ro
      - ${DEPLOY_DIR}/images:/images
