STONE_PROVISIONING ?= "img sd emmc"
MACHINEOVERRIDES =. "nanopi-r5s:"

require conf/machine/include/avocado.inc
require conf/machine/include/rk3568.inc
require conf/machine/include/avocado-rockchip.inc

KERNEL_DEVICETREE = "rockchip/rk3568-nanopi-r5s.dtb"
UBOOT_MACHINE     = "nanopi-r5s-rk3568_defconfig"

MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"

ROOTFS_IMAGE_EXTRA_INSTALL += "linux-firmware-rtl-nic"

INITRAMFS_IMAGE_EXTRA_INSTALL += "linux-firmware-rtl-nic"

UBOOT_EXTLINUX_KERNEL_ARGS:append = " consoleblank=0"
