inherit cargo cargo-update-recipe-crates

SRCREV = "38fcac0f3668986727aa7ba6290e8cb94c1dbe5f"
SRC_URI = "git://github.com/astral-sh/uv.git;protocol=https;nobranch=1"

require ${BPN}-crates.inc

S = "${WORKDIR}/git"

CARGO_SRC_DIR = ""

LIC_FILES_CHKSUM = " \
    file://LICENSE-APACHE;md5=86d3f3a95c324c9479bd8986968f4327 \
    file://LICENSE-MIT;md5=45674e482567aa99fe883d3270b11184 \
"

SUMMARY = "An extremely fast Python package and project manager, written in Rust"
HOMEPAGE = "https://github.com/astral-sh/uv"
LICENSE = "Apache-2.0 | MIT"

# Cargo release builds strip binaries by default
INSANE_SKIP:${PN} += "already-stripped"

# Override do_update_crates to only use the root Cargo.lock
# The default implementation walks all subdirectories and fails on test packages
do_update_crates() {
    TARGET_FILE="${THISDIR}/${BPN}-crates.inc"

    nativepython3 - <<EOF
import tomllib
import os

def get_crates(f):
    c_list = '# from Cargo.lock'
    c_list += '\nSRC_URI += " \\\\'
    crates = tomllib.load(open(f, 'rb'))

    crates_candidates = list(filter(lambda c: 'crates.io' in c.get('source', ''), crates['package']))

    if not crates_candidates:
        raise ValueError("Unable to find any candidate crates that use crates.io")

    cksum_list = ''
    for c in crates_candidates:
        rename = "%s-%s" % (c['name'], c['version'])
        c_list += '\n    crate://crates.io/%s/%s \\\\' % (c['name'], c['version'])
        if 'checksum' in c:
            cksum_list += '\nSRC_URI[%s.sha256sum] = "%s"' % (rename, c['checksum'])

    c_list += '\n"\n'
    c_list += cksum_list
    c_list += '\n'
    return c_list

# Only process the root Cargo.lock, not test packages
cargo_lock = os.path.join('${S}', 'Cargo.lock')
if not os.path.exists(cargo_lock):
    raise ValueError("Cannot find Cargo.lock at %s" % cargo_lock)

crates = "# Autogenerated with 'bitbake -c update_crates ${PN}'\n\n"
crates += get_crates(cargo_lock)
open("${TARGET_FILE}", 'w').write(crates)
EOF

    bbnote "Successfully update crates inside '${TARGET_FILE}'"
}

BBCLASSEXTEND = "native nativesdk"
