#@TYPE: Machine
#@NAME: Nvidia Jetson AGX Orin dev kit
#@DESCRIPTION: Nvidia Jetson AGX Orin dev kit (P3701-0000 module in P3737-0000 carrier)

require conf/machine/include/avocado-jetson.inc
require conf/machine/include/avocado.inc

TEGRA_BUPGEN_SPECS ?= "fab=300;boardsku=0000;boardrev=;chipsku=00:00:00:D0;bup_type=bl \
                       fab=300;boardsku=0000;boardrev=;bup_type=kernel"
KERNEL_DEVICETREE ?= "tegra234-p3737-0000+p3701-0000-nv.dtb"

MACHINEOVERRIDES =. "jetson-agx-orin-devkit:"
AVOCADO_VAR_PART_DEV = "/dev/nvme0n1p16"

TNSPEC_BOOTDEV ?= "nvme0n1p1"
TEGRA_BOARDSKU ?= "0005"

PARTITION_LAYOUT_TEMPLATE_DEFAULT_SUPPORTS_REDUNDANT ?= "1"
PARTITION_LAYOUT_EXTERNAL_DEFAULT ?= "flash_l4t_t234_nvme.xml"

require conf/machine/include/agx-orin.inc
require conf/machine/include/devkit-wifi.inc

KERNEL_ARGS:append = " audit=0 nvme_core.default_ps_max_latency_us=0 pcie_aspm=off"
KERNEL_MODULE_AUTOLOAD:append = " nvme"
