#@TYPE: Machine
#@NAME: QEMU ARM64 machine
#@DESCRIPTION: Machine configuration for running an ARM64 system on QEMU

require conf/machine/include/avocado.inc

BOOTVARS = "ubootenv"
MACHINEOVERRIDES =. "bootvars-${BOOTVARS}:qemuarm64-secureboot:qemuarm64:"

require ${COREBASE}/meta/conf/machine/qemuarm64.conf

KMACHINE = "qemuarm64"

UBOOT_ENV_SIZE = "0x20000"

# secure=on can't ever use KVM, so force it off
QEMU_USE_KVM = ""

QB_MACHINE = "-machine virt,secure=on,acpi=off"
QB_MEM = "-m 1024"
QB_DEFAULT_FSTYPE = "wic.qcow2"
QB_DEFAULT_BIOS = "flash.bin"
QB_FSINFO = "wic:no-kernel-in-fs"
QB_ROOTFS_OPT = ""
QB_KERNEL_ROOT = "/dev/vda2"

WKS_FILE ?= "avocado-qemuarm64.wks"
DEPENDS:append:pn-avocado-image-genimage = " trusted-firmware-a"
IMAGE_BOOT_FILES = "${KERNEL_IMAGETYPE}"

MACHINE_FEATURES += "genimage optee-ftpm"
