default avocado-a
timeout 1
prompt 0

label avocado-a
  kernel /Image
  fdt /r9a09g056n48-hummingboard-iiot.dtb
  fdtoverlays /rzv2n-hummingboard-iiot-panel-dsi-WJ70N3TYJHMNG0.dtbo /rzv2n-hummingboard-iiot-csi-camera-imx678.dtbo
  initrd /avocado-image-initramfs-rzv2n-sr-som.cpio.zst
  append console=ttySC0,115200 earlycon rw rootwait
