# /etc/ganesha/ganesha.conf
LOG {
  Default_Log_Level = EVENT;
}

NFS_Core_Param {
  NFS_Port = 12049;
  Enable_NLM = false;
  Enable_RQUOTA = false;
  Enable_UDP = false;
  Protocols = 4;
  allow_set_io_flusher_fail = true;
  Nb_Max_Fd = 65536;
  Max_Open_Files = 10000;
  DRC_Max_Size = 32768;
  Attr_Expiration_Time = 60;
  Nb_Worker = 256;
  Bind_addr = 0.0.0.0;
}

NFSV4 {
  Graceless = false;
  Allow_Numeric_Owners = true;
  Only_Numeric_Owners = true;
}

# Defaults that all EXPORT{} blocks inherit unless they override
EXPORT_DEFAULTS {
  Access_Type = RW;
  Squash = No_Root_Squash;
  Transports = TCP;
  Protocols = 4;
  SecType = none;
  Disable_ACL = true;
  Manage_Gids = false;
  Anonymous_uid = 0;
  Anonymous_gid = 0;

  CLIENT {
    Clients = *;
    Access_Type = RO;
  }
}
