DEFAULT avocado
TIMEOUT 10
PROMPT 0
MENU TITLE Avocado Boot Menu

LABEL avocado
    MENU LABEL Avocado Linux
    LINUX /Image
    INITRD /avocado-initramfs.cpio.zst
    FDT /rockchip/rk3588-orangepi-5-plus.dtb
    APPEND console=ttyS2,1500000n8 root=PARTUUID=28e6c982-d097-43ce-a3ab-b9baba37de78 rootfstype=erofs ro audit=0
