header:
  version: 16

env:
  AVOCADO_REPO_BASE: "http://package-repo"
  DISTRO_CODENAME: "dev"
  DISTRO_VERSION: "0.1.0"
  BB_GIT_SHALLOW: "0"
  BB_GENERATE_SHALLOW_TARBALLS: "1"
  BB_GIT_SHALLOW_DEPTH: "1"
  SDKMACHINE: "x86_64"

build_system: oe

repos:
  bitbake:
    url: https://git.openembedded.org/bitbake
    branch: '2.8'
    commit: 696c2c1ef095f8b11c7d2eff36fae50f58c62e5e
    layers:
      .: excluded

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    branch: scarthgap
    commit: 491671faee11ea131feab5a3a451d1a01deb2ab1
    layers:
      meta-oe:
      meta-perl:
      meta-python:
      meta-networking:
      meta-filesystems:
      meta-multimedia:

  openembedded-core:
    url: https://git.openembedded.org/openembedded-core
    branch: scarthgap
    commit: 29d920f4c2249df7a69f00100924b4525e03c0d9
    layers:
      meta:

  meta-ptx:
    url: https://github.com/pengutronix/meta-ptx.git
    branch: scarthgap
    commit: 1189ee566604d7439e824242825da29ae3729ae5
    layers:
      .:


  meta-avocado:
    path: meta-avocado
    layers:
      meta-avocado:

distro: avocado

local_conf_header:
  meta-avocado: |
    USER_CLASSES:append = " buildhistory buildstats buildstats-summary"

    ## Debugging prior to extensions loading
    #EXTRA_IMAGE_FEATURES += " allow-empty-password allow-root-login empty-root-password post-install-logging"
    #EXTRA_INITRAMFS_FEATURES += " allow-empty-password allow-root-login empty-root-password post-install-logging"
    ## Debugging Extensions
    #ROOTFS_IMAGE_EXTRA_INSTALL:append = " avocado-extension-debug-tweaks"

  sdk: |
    CONF_VERSION = "2"
