header:
  version: 16
  includes:
  - repo: meta-avocado
    file: kas/vendor/oe.yml
  - repo: meta-avocado
    file: kas/vendor/ptx.yml
  - repo: meta-avocado
    file: kas/vendor/fwup.yml

env:
  AVOCADO_REPO_BASE: "http://package-repo"
  DISTRO_CODENAME: "dev"
  DISTRO_VERSION: "0.1.0"
  PARALLEL_MAKE_HIGHMEM: ""
  SDKMACHINE: "x86_64"

repos:
  meta-openembedded:
    url: https://github.com/avocado-linux/vendor-meta-openembedded
    path: meta-openembedded
    branch: scarthgap
    commit: b9fb6556a3c8a3e477dce334205b658cb79ad501
    layers:
      meta-oe:
      meta-perl:
      meta-python:
      meta-networking:
      meta-filesystems:
      meta-multimedia:

  meta-lts-mixins:
    url: https://github.com/avocado-linux/vendor-meta-lts-mixins
    path: meta-lts-mixins
    branch: scarthgap/rust
    commit: a0705b87e7c1a257dafb089063f3302ed49c87d3
    layers:
      .:

  meta-avocado:
    path: meta-avocado
    layers:
      meta-avocado:
      meta-avocado-shared:

distro: avocado

local_conf_header:
  meta-avocado: |
    USER_CLASSES:append = " buildhistory buildstats buildstats-summary"

    ## Debugging prior to extensions loading
    AVOCADO_ALLOW_ROOT_LOGIN = "1"
    LICENSE_FLAGS_ACCEPTED:append = " commercial_gstreamer1.0-plugins-ugly commercial_mpeg2dec"

  sdk: |
    CONF_VERSION = "2"
