header:
  version: 11
  includes:
  - repo: meta-avocado
    file: kas/extra/atecc.yml

build_system: oe

repos:
  bitbake:
    url: https://git.openembedded.org/bitbake
    branch: '2.8'
    commit: 696c2c1ef095f8b11c7d2eff36fae50f58c62e5e
    layers:
      .: excluded

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    branch: scarthgap
    commit: e92d0173a80ea7592c866618ef5293203c50544c
    layers:
      meta-oe:
      meta-perl:
      meta-python:
      meta-networking:
      meta-filesystems:
      meta-multimedia:

  openembedded-core:
    url: https://git.openembedded.org/openembedded-core
    branch: scarthgap
    commit: b214cc84a922f7a3fb7ebbc501189ce25e8bd2bd
    layers:
      meta:

  meta-avocado:
    path: meta-avocado
    layers:
      meta-avocado:

distro: avocado

local_conf_header:
  meta-avocado: |
    USER_CLASSES:append = " buildhistory buildstats buildstats-summary"
    AVOCADO_REPO_BASE = "http://package-repo"

    ## Debugging prior to extensions loading
    #EXTRA_IMAGE_FEATURES += " allow-empty-password allow-root-login empty-root-password post-install-logging"
    #EXTRA_INITRAMFS_FEATURES += " allow-empty-password allow-root-login empty-root-password post-install-logging"
    ## Debugging Extensions
    #ROOTFS_IMAGE_EXTRA_INSTALL:append = " avocado-extension-debug-tweaks"

  sdk: |
    CONF_VERSION = "2"
