header:
  version: 11
  includes:
    - kas/extra/atecc.yml

build_system: oe

repos:
  bitbake:
    url: https://git.openembedded.org/bitbake
    branch: '2.8'
    layers:
      .: excluded

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    branch: scarthgap
    layers:
      meta-oe:
      meta-perl:
      meta-python:
      meta-networking:
      meta-filesystems:
      meta-multimedia:

  openembedded-core:
    url: https://git.openembedded.org/openembedded-core
    branch: scarthgap
    layers:
      meta:

  meta-avocado:
    path: meta-avocado
    layers:
      meta-avocado:

distro: avocado

local_conf_header:
  meta-avocado: |
    USER_CLASSES:append = " buildhistory buildstats buildstats-summary"
    EXTRA_IMAGE_FEATURES += " allow-empty-password allow-root-login empty-root-password post-install-logging"
    AVOCADO_REPO_BASE = "http://package-repo"

  sdk: |
    CONF_VERSION = "2"
