#!/usr/bin/env bash

set -e

hook="avocado-provision"
target="$AVOCADO_TARGET"

RUNTIME_NAME="$1"

input_dir="$AVOCADO_PREFIX/output/runtimes/$RUNTIME_NAME/stone"
manifest="$AVOCADO_PREFIX/sdk/stone/stone-${target}.json"

echo -e "\033[94m[INFO]\033[0m Running stone provision.
  Input directory:  ${input_dir}"

stone \
  provision \
  -i "$input_dir"

echo -e "\033[92m[SUCCESS]\033[0m Successfully ran SDK lifecycle hook '$hook' for target '$target'."
exit 0
