#!/usr/bin/env bash

set -e

hook="avocado-deploy"
target="$AVOCADO_TARGET"

runtime="$AVOCADO_RUNTIME" 
machine="$AVOCADO_DEPLOY_MACHINE"

ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

rsync -av --delete -e "ssh ${ssh_opts}" ${AVOCADO_PREFIX}/output/extensions/ root@${machine}:/var/lib/avocado/extensions/
cat ${AVOCADO_PREFIX}/output/runtimes/${runtime}/stone/_build/avocado-${target}-rootdisk.zip | ssh ${ssh_opts} root@${machine} 'fwup -a -U -d /dev/mmcblk0 -t upgrade && reboot'

echo -e "\033[92m[SUCCESS]\033[0m Successfully ran SDK lifecycle hook '$hook' for target '$target'."
exit 0
