# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-avocado-synaptics"
BBFILE_PATTERN_meta-avocado-synaptics = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-avocado-synaptics = "9"

LAYERDEPENDS_meta-avocado-synaptics = "core"
LAYERSERIES_COMPAT_meta-avocado-synaptics = "scarthgap"
