name: "Stage Avocado Repos"
description: "Initialize and stage RPM repositories with build RPMs"
inputs:
  machine:
    description: "Machine to stage RPMs for (e.g. qemux86-64)"
    required: true
  repo_base_path:
    description: "Full path for repository staging"
    required: true
runs:
  using: "composite"
  steps:
    - name: Map built repos to deploy directories
      shell: bash
      run: |
        echo "Staging repos for ${{ inputs.machine }} to ${{ inputs.repo_base_path }}"
        ./scripts/repo-stage-rpms.sh ./build-${{ inputs.machine }}/build/tmp/deploy/rpm ${{ inputs.repo_base_path }}
