BOOTVARS = "ubootenv"
STONE_PROVISIONING ?= "img usb usb-emmc usb-nvme"
MACHINEOVERRIDES =. "bootvars-${BOOTVARS}:seeed-reterminal-dm:reterminal-dm:seeed:cm4:"

VC4DTBO ?= "vc4-kms-v3d-pi4"

PREFERRED_VERSION_linux-raspberrypi ?= "6.12%"

require conf/machine/avocado-raspberrypi4.conf

IMAGE_BOOT_FILES:append = " devicetree/reTerminal-DM.dtbo;overlays/reTerminal-DM.dtbo"

RPI_KERNEL_DEVICETREE_OVERLAYS:append = " \
  overlays/i2c0.dtbo \
  overlays/i2c1.dtbo \
  overlays/i2c3.dtbo \
  overlays/i2c6.dtbo \
  overlays/vc4-kms-v3d-pi4.dtbo \
"

ENABLE_SPI = "1"
ENABLE_I2C = "1"
ENABLE_UART = "1"

CMDLINE:append = " vc4.force_hotplug=1 video=HDMI-A-1:d"

PACKAGECONFIG:append:pn-qtbase = " eglfs "
KERNEL_MODULE_AUTOLOAD:rpi += "i2c-dev spi-dev"
