FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  direnv \
  sudo \
  tmux \
  build-essential \
  chrpath \
  cpio \
  debianutils \
  diffstat \
  file \
  gawk \
  gcc \
  git \
  git-lfs \
  iputils-ping \
  libacl1 \
  liblz4-tool \
  locales \
  python3 \
  python3-git \
  python3-jinja2 \
  python3-pexpect \
  python3-pip \
  python3-subunit \
  socat \
  texinfo \
  unzip \
  wget \
  xz-utils \
  zstd && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8 && \
  update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

RUN echo 'eval "$(direnv hook bash)"' >> /etc/bash.bashrc

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN pip install --no-cache-dir kas

ARG USER_ID=1000
ARG GROUP_ID=1000

ENV USER_NAME=avocado
ENV DL_DIR=/avocado/dl
ENV SSTATE_DIR=/avocado/sstate
ENV BB_ENV_PASSTHROUGH_ADDITIONS="DL_DIR SSTATE_DIR"

RUN useradd -m -s /bin/bash $USER_NAME
RUN echo "avocado ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN mkdir -p /avocado/build /avocado/sstate /avocado/dl && chown -R avocado:avocado /avocado
RUN echo "root  ALL = NOPASSWD: /bin/su ALL" >> /etc/sudoers

USER avocado

WORKDIR /avocado-build
CMD ["/bin/bash"]
