#!/usr/bin/env bash

set -e

hook="avocado-provision"
target="imx93-frdm"

echo -e "\033[94m[INFO]\033[0m SDK lifecycle hook '$hook' for target '$target' is a no-op."
echo -e "\033[92m[SUCCESS]\033[0m Successfully ran SDK lifecycle hook '$hook' for target '$target'."
exit 0
