#!/usr/bin/env bash

set -e

hook="avocado-build"
target="imx93-evk"

RUNTIME_NAME="$1"

output_dir="$AVOCADO_PREFIX/output/runtimes/$RUNTIME_NAME"

mkdir -p "$output_dir"

input_dir="$AVOCADO_PREFIX/runtimes/$RUNTIME_NAME/deploy"
output_dir="$AVOCADO_PREFIX/output/runtimes/$RUNTIME_NAME/stone"
manifest="$AVOCADO_PREFIX/sdk/stone/stone-${target}.json"

echo -e "\033[94m[INFO]\033[0m Running stone validate.
  Manifest:        ${manifest}
  Input directory: ${input_dir}"

stone \
  validate \
  -m "${manifest}" \
  -i "$input_dir"

echo -e "\033[94m[INFO]\033[0m Running stone create.
  Manifest:         ${manifest}
  Input directory:  ${input_dir}
  Output directory: ${output_dir}"

stone \
  create \
  --os-release "${AVOCADO_PREFIX}/rootfs/usr/lib/os-release" \
  -m $manifest \
  -i "$input_dir" \
  -o "$output_dir"

echo -e "\033[92m[SUCCESS]\033[0m Successfully ran SDK lifecycle hook '$hook' for target '$target'."
exit 0
