#!/usr/bin/env bash
# Script to run QEMU with TPM support via kas
# Usage: ./run-qemu-tpm
# Assumes pwd is build directory

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$(pwd)/build"
SYSROOT_COMPONENTS_DIR="$BUILD_DIR/tmp/sysroots-components/x86_64"
SYSROOT_UNINATIVE_DIR="$BUILD_DIR/tmp/sysroots-uninative"

# Image paths relative to build directory
MACHINE="avocado-qemux86-64"
DEPLOY_DIR="$BUILD_DIR/tmp/deploy/images/$MACHINE"
IMAGE_NAME="avocado-image-genimage-$MACHINE.img"
QEMU_BIOS="${DEPLOY_DIR}/u-boot.rom"
QEMU_IMG="$BUILD_DIR/tmp/sysroots-components/x86_64/qemu-system-native/usr/bin/qemu-img"
QEMU_EXEC="$BUILD_DIR/tmp/sysroots-components/x86_64/qemu-system-native/usr/bin/qemu-system-x86_64"
LIB_PATH=$("$SCRIPT_DIR/find-library-path" $QEMU_EXEC $SYSROOT_COMPONENTS_DIR $SYSROOT_UNINATIVE_DIR)
echo "LIB_PATH=$LIB_PATH"
echo "Starting QEMU..."
echo "-------------------------------------"

LD_LIBRARY_PATH="$LIB_PATH" "$QEMU_IMG" resize -f raw "$DEPLOY_DIR/$IMAGE_NAME" 1024M

# Run QEMU with TPM support
LD_LIBRARY_PATH="$LIB_PATH" "$QEMU_EXEC" \
  -bios "${QEMU_BIOS}" \
  -device sdhci-pci \
  -device sd-card,drive=mmc \
  -drive file="$DEPLOY_DIR/$IMAGE_NAME",if=none,format=raw,id=mmc \
  -m 256 \
  -cpu max \
  -nographic
