#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$(pwd)/build"

SYSROOT_COMPONENTS_DIR="$BUILD_DIR/tmp/sysroots-components/x86_64"
SYSROOT_UNINATIVE_DIR="$BUILD_DIR/tmp/sysroots-uninative"

# Image paths relative to build directory
MACHINE_SHORT_NAME="qemuarm64"
MACHINE="avocado-${MACHINE_SHORT_NAME}"
DEPLOY_DIR="$BUILD_DIR/tmp/deploy/stone/_build"
IMAGE_NAME="${MACHINE}-rootdisk.img"
IMAGE_FILE="$DEPLOY_DIR/$IMAGE_NAME"
QEMU_BIOS="${DEPLOY_DIR}/flash.bin"
QEMU_EXEC="$BUILD_DIR/tmp/sysroots-components/x86_64/qemu-system-native/usr/bin/qemu-system-aarch64"
QEMU_IMG="$BUILD_DIR/tmp/sysroots-components/x86_64/qemu-system-native/usr/bin/qemu-img"
LIB_PATH=$("$SCRIPT_DIR/find-library-path" $QEMU_EXEC $SYSROOT_COMPONENTS_DIR $SYSROOT_UNINATIVE_DIR)
echo "LIB_PATH=$LIB_PATH"
echo "Starting QEMU ARM64..."
echo "-------------------------------------"

LD_LIBRARY_PATH="$LIB_PATH" "$QEMU_IMG" resize -f raw "$IMAGE_FILE" 1024M

# Run QEMU with proper drive configuration
LD_LIBRARY_PATH="$LIB_PATH" "$QEMU_EXEC" \
  -m 1024 \
  -cpu cortex-a53 \
  -bios "${QEMU_BIOS}" \
  -device sdhci-pci \
  -device sd-card,drive=mmc \
  -drive file="$IMAGE_FILE",if=none,format=raw,id=mmc \
  -M virt,secure=on,highmem=off,acpi=off \
  -nographic
