#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Get the directory where this script is located
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# Source the common functions
source "${SCRIPT_DIR}/avocado-sdk-common.sh"

# Define the main function that will run in the SDK environment
run_dnf_command() {
    if [ "$1" = "sdk" ]; then
        shift
        $DNF_SDK_HOST $@
    elif [ "$1" = "images" ]; then
        $DNF_SDK_HOST --installroot=/opt/_avocado/images install \
            nativesdk-avocado-pkg-img-rootfs \
            nativesdk-avocado-pkg-img-initramfs
    elif [ "$1" = "bootfiles" ]; then
        $DNF_SDK_HOST --installroot=/opt/_avocado/bootfiles install \
            nativesdk-avocado-pkg-bootfiles
    else
        $DNF_SDK_HOST --installroot=${AVOCADO_SDK_SYSROOTS}/$1 ${@:2}
    fi
}

# Run the main function in the SDK environment
run_in_sdk_env run_dnf_command "$@"
