#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

# Get the directory where this script is located
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# Source the common functions
source "${SCRIPT_DIR}/avocado-sdk-common.sh"

# Define the main function that will run in the SDK environment

if [ "$1" = "sdk" ]; then
    run_dnf_command() {
        shift
        env -i TERM="$TERM" \
            DNF_SDK_HOST="$DNF_SDK_HOST" \
            RPM_ETCCONFIGDIR="$AVOCADO_SDK_PREFIX" \
            RPM_NO_CHROOT_FOR_SCRIPTS=1 \
            DNF_SDK_HOST_OPTS="$DNF_SDK_HOST_OPTS" \
            DNF_SDK_REPO_CONF="$DNF_SDK_REPO_CONF" \
            $DNF_SDK_HOST $DNF_SDK_HOST_OPTS $DNF_SDK_REPO_CONF $@
    }
    run_in_sdk_env run_dnf_command "$@"
elif [ "$1" = "images" ]; then
    env -i TERM="$TERM" \
        DNF_SDK_HOST="$DNF_SDK_HOST" \
        AVOCADO_SDK_PREFIX="$AVOCADO_SDK_PREFIX" \
        RPM_CONFIGDIR="$AVOCADO_SDK_PREFIX/usr/lib/rpm" \
        RPM_ETCCONFIGDIR="$DNF_SDK_TARGET_PREFIX" \
        DNF_SDK_HOST_OPTS="$DNF_SDK_HOST_OPTS" \
        DNF_SDK_TARGET_REPO_CONF="$DNF_SDK_TARGET_REPO_CONF" \
        RPM_NO_CHROOT_FOR_SCRIPTS=1 \
        $DNF_SDK_HOST $DNF_SDK_HOST_OPTS $DNF_SDK_TARGET_REPO_CONF --installroot=${AVOCADO_PREFIX}/images install \
        avocado-img-initramfs avocado-img-rootfs avocado-img-var avocado-img-bootfiles
else
    env -i \
        TERM="$TERM" \
        DNF_SDK_HOST="$DNF_SDK_HOST" \
        AVOCADO_SDK_PREFIX="$AVOCADO_SDK_PREFIX" \
        RPM_CONFIGDIR="$AVOCADO_SDK_PREFIX/usr/lib/rpm" \
        RPM_ETCCONFIGDIR="$DNF_SDK_TARGET_PREFIX" \
        DNF_SDK_HOST_OPTS="$DNF_SDK_HOST_OPTS" \
        DNF_SDK_TARGET_REPO_CONF="$DNF_SDK_TARGET_REPO_CONF" \
        RPM_NO_CHROOT_FOR_SCRIPTS=1 \
        $DNF_SDK_HOST $DNF_SDK_HOST_OPTS $DNF_SDK_TARGET_REPO_CONF --installroot=${AVOCADO_PREFIX}/$1 ${@:2}
fi
