#!/usr/bin/env bash

# environment-setup is generated into the SDK prefix at install time, so it is
# not present in this layer for shellcheck to follow.
# shellcheck disable=SC1091
. "${AVOCADO_SDK_PREFIX}/environment-setup"
