default avocado-a
timeout 1
prompt 0

label avocado-a
  kernel /Image
  fdt /stm32mp257f-dk-ca35tdcid-ostl.dtb
  initrd /avocado-image-initramfs-stm32mp25-dk.cpio.zst
  append console=ttySTM0,115200 earlycon ro rootwait root=PARTUUID=a7b8c9da-e0f1-40b1-a213-6e7f8091a2b3 rootfstype=erofs
