name: Dispatch Build and Deploy

on:
  workflow_dispatch:
    inputs:
      machine:
        description: 'Target machine to build and deploy'
        required: true
        default: 'reterminal'
        type: string

jobs:
  build:
    runs-on: molcajete
    env:
      DISTRO_VERSION: "0.1.0"
      DISTRO_CODENAME: "apollo/edge"
      AVOCADO_REPO_BASE: "https://repo.avocadolinux.org"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build target machine
        uses: ./.github/actions/avocado-build
        with:
          machine: ${{ github.event.inputs.machine }}

      - name: Deploy target repos
        uses: ./.github/actions/avocado-deploy
        with:
          machine: ${{ github.event.inputs.machine }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 and Replace Contents
        run: |
          # Upload contents to S3
          aws s3 sync /home/runner/_cache/repos s3://${{ secrets.AWS_S3_BUCKET }}/

