name: Edge Build and Deploy

on:
  schedule:
    - cron: '0 5 * * *' # Runs at 5 AM UTC daily
  workflow_dispatch:
    inputs:
      build_all:
        description: 'Build all machines and perform all tasks'
        type: boolean
        default: false
      target_to_build:
        description: 'Select the machine to build'
        type: choice
        required: true
        options:
          # Machines
          - imx91-frdm
          - imx93-frdm
          - qemux86-64
          - reterminal
          - imx93-evk
          - jetson-orin-nano-devkit-nvme
          - raspberrypi4

jobs:
  determine_build_matrix:
    runs-on: molcajete
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Determine build parameters
        id: set-matrix
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const allMachinesList = [
              "imx91-frdm", "imx93-frdm", "qemux86-64",
              "reterminal", "imx93-evk", "jetson-orin-nano-devkit-nvme", "raspberrypi4"
            ];

            let selectedMachines = [];

            if (context.eventName === 'schedule') {
              selectedMachines = allMachinesList;
              core.info('Scheduled run: Selecting all machines.');
            } else if (context.eventName === 'workflow_dispatch') {
              const buildAll = context.payload.inputs.build_all === true || context.payload.inputs.build_all === 'true';

              if (buildAll) {
                selectedMachines = allMachinesList;
                core.info('Build all selected: Building all machines.');
              } else {
                const target = context.payload.inputs.target_to_build;
                core.info(`Dispatch input target_to_build: ${target}`);

                if (allMachinesList.includes(target)) {
                  selectedMachines = [target];
                  core.info(`Selected machine for dispatch: ${target}`);
                } else {
                  core.warning(`Unknown target selected: ${target}. No machine will be built.`);
                }
              }
            } else {
              core.setFailed(`Unsupported event: ${context.eventName}`);
              return;
            }
            core.setOutput('matrix', JSON.stringify(selectedMachines));

  build:
    needs: determine_build_matrix
    if: needs.determine_build_matrix.outputs.matrix != '[]'
    runs-on: molcajete
    strategy:
      fail-fast: false
      matrix:
        machine: ${{ fromJSON(needs.determine_build_matrix.outputs.matrix) }}
        build_config:
          - target: avocado-distro
            sdk_machine: x86_64
          - target: avocado-sdk
            sdk_machine: x86_64
          - target: avocado-sdk
            sdk_machine: aarch64
    env:
      DISTRO_CODENAME: "apollo/edge"
      DISTRO_VERSION: "0.1.0"
      AVOCADO_REPO_BASE: "https://repo.avocadolinux.org"
      LOCAL_REPO_AGGREGATION_PATH: "/home/runner/_cache/repos"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create local repo aggregation directory
        run: mkdir -p ${{ env.LOCAL_REPO_AGGREGATION_PATH }}

      - name: Build ${{ matrix.build_config.target }} for ${{ matrix.machine }}
        uses: ./.github/actions/avocado-build
        with:
          machine: ${{ matrix.machine }}
          target: ${{ matrix.build_config.target }}
          sdk_machine: ${{ matrix.build_config.sdk_machine }}

      - name: Stage target repos for ${{ matrix.machine }}
        uses: ./.github/actions/avocado-stage-repo
        with:
          machine: ${{ matrix.machine }}

  cleanup_repos:
    needs:
      - determine_build_matrix
      - build
    if: needs.build.result == 'success'
    runs-on: molcajete
    env:
      REPO_BASE_PATH: "/home/runner/_cache/repos"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make cleanup script executable
        run: chmod +x ./scripts/repo-purge-window.sh

      - name: Run cleanup script on aggregated repos
        run: |
          echo "Running cleanup script on ${{ env.REPO_BASE_PATH }}"
          ./scripts/repo-purge-window.sh "${{ env.REPO_BASE_PATH }}"

  update_repo_metadata:
    needs:
      - determine_build_matrix
      - build
      - cleanup_repos
    if: needs.build.result == 'success'
    runs-on: molcajete
    env:
      REPO_BASE_PATH: "/home/runner/_cache/repos"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update repository metadata
        run: |
          echo "Updating repository metadata in ${{ env.REPO_BASE_PATH }}"
          ./scripts/repo-update-metadata.sh "${{ env.REPO_BASE_PATH }}"

  sync_to_s3:
    needs: [determine_build_matrix, build, cleanup_repos, update_repo_metadata]
    if: needs.build.result == 'success'
    runs-on: molcajete
    env:
      REPO_BASE_PATH: "/home/runner/_cache/repos"
      S3_BUCKET_PATH: ${{ secrets.AWS_S3_BUCKET }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync cleaned and aggregated repos to S3
        run: |
          echo "Syncing repositories from ${{ env.REPO_BASE_PATH }} to s3://${{ env.S3_BUCKET_PATH }}"
          aws s3 sync --delete "${{ env.REPO_BASE_PATH }}" "s3://${{ env.S3_BUCKET_PATH }}"
          echo "S3 sync complete."
